# COVID-19 Data Exploration Project

## Data cleaning

In [1]:
# import packages
import numpy as np
import pandas as pd

In [2]:
# import data and check
df = pd.read_csv('./data/owid-covid-data.csv')
df

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,5.0,5.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,5.0,0.0,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120326,ZWE,Africa,Zimbabwe,2021-09-26,129625.0,120.0,241.000,4604.0,1.0,5.286,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
120327,ZWE,Africa,Zimbabwe,2021-09-27,129919.0,294.0,247.571,4607.0,3.0,5.429,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
120328,ZWE,Africa,Zimbabwe,2021-09-28,130272.0,353.0,298.000,4615.0,8.0,6.571,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
120329,ZWE,Africa,Zimbabwe,2021-09-29,130485.0,213.0,240.143,4616.0,1.0,3.429,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
120330,ZWE,Africa,Zimbabwe,2021-09-30,130820.0,335.0,240.857,4623.0,7.0,3.286,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [74]:
# basic info; check nulls and dtype
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120331 entries, 0 to 120330
Data columns (total 65 columns):
 #   Column                                   Non-Null Count   Dtype
---  ------                                   --------------   -----
 0   iso_code                                 120331 non-null  object
 1   continent                                114843 non-null  object
 2   location                                 120331 non-null  object
 3   date                                     120331 non-null  object
 4   total_cases                              114306 non-null  float64
 5   new_cases                                114303 non-null  float64
 6   new_cases_smoothed                       113288 non-null  float64
 7   total_deaths                             103538 non-null  float64
 8   new_deaths                               103693 non-null  float64
 9   new_deaths_smoothed                      113288 non-null  float64
 10  total_cases_per_million                  113704 non-null  float64
 11  new_cases_per_million                    113701 non-null  float64
 12  new_cases_smoothed_per_million           112691 non-null  float64
 13  total_deaths_per_million                 102949 non-null  float64
 14  new_deaths_per_million                   103104 non-null  float64
 15  new_deaths_smoothed_per_million          112691 non-null  float64
 16  reproduction_rate                        97024 non-null   float64
 17  icu_patients                             13674 non-null   float64
 18  icu_patients_per_million                 13674 non-null   float64
 19  hosp_patients                            15728 non-null   float64
 20  hosp_patients_per_million                15728 non-null   float64
 21  weekly_icu_admissions                    1253 non-null    float64
 22  weekly_icu_admissions_per_million        1253 non-null    float64
 23  weekly_hosp_admissions                   2151 non-null    float64
 24  weekly_hosp_admissions_per_million       2151 non-null    float64
 25  new_tests                                51915 non-null   float64
 26  total_tests                              51988 non-null   float64
 27  total_tests_per_thousand                 51988 non-null   float64
 28  new_tests_per_thousand                   51915 non-null   float64
 29  new_tests_smoothed                       62362 non-null   float64
 30  new_tests_smoothed_per_thousand          62362 non-null   float64
 31  positive_rate                            59043 non-null   float64
 32  tests_per_case                           58403 non-null   float64
 33  tests_units                              64281 non-null   object
 34  total_vaccinations                       27368 non-null   float64
 35  people_vaccinated                        26035 non-null   float64
 36  people_fully_vaccinated                  22988 non-null   float64
 37  total_boosters                           2884 non-null    float64
 38  new_vaccinations                         22691 non-null   float64
 39  new_vaccinations_smoothed                48617 non-null   float64
 40  total_vaccinations_per_hundred           27368 non-null   float64
 41  people_vaccinated_per_hundred            26035 non-null   float64
 42  people_fully_vaccinated_per_hundred      22988 non-null   float64
 43  total_boosters_per_hundred               2884 non-null    float64
 44  new_vaccinations_smoothed_per_million    48617 non-null   float64
 45  stringency_index                         100210 non-null  float64
 46  population                               119515 non-null  float64
 47  population_density                       111264 non-null  float64
 48  median_age                               106279 non-null  float64
 49  aged_65_older                            105097 non-null  float64
 50  aged_70_older                            105696 non-null  float64
 51  gdp_per_capita                           106899 non-null  float64
 52  extreme_poverty                          71730 non-null   float64
 53  cardiovasc_death_rate                    106558 non-null  float64
 54  diabetes_prevalence                      109860 non-null  float64
 55  female_smokers                           83200 non-null   float64
 56  male_smokers                             81992 non-null   float64
 57  handwashing_facilities                   53541 non-null   float64
 58  hospital_beds_per_thousand               96889 non-null   float64
 59  life_expectancy                          114154 non-null  float64
 60  human_development_index                  106654 non-null  float64
 61  excess_mortality_cumulative_absolute     4129 non-null    float64
 62  excess_mortality_cumulative              4129 non-null    float64
 63  excess_mortality                         4275 non-null    float64
 64  excess_mortality_cumulative_per_million  4129 non-null    float64
dtypes: float64(60), object(5)
memory usage: 59.7+ MB

### Cleaning operations

- Create 2 tables:
    1. **`covid_deaths`**
        - Move the `population` column to be after the `date` column to avoid performing a join with every query
        - Drop the following columns:
            - `'new_tests', 'total_tests', 
    'total_tests_per_thousand', 'new_tests_per_thousand',
    'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
    'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
    'people_vaccinated', 'people_fully_vaccinated', 'total_boosters',
    'new_vaccinations', 'new_vaccinations_smoothed',
    'total_vaccinations_per_hundred', 'people_vaccinated_per_hundred',
    'people_fully_vaccinated_per_hundred', 'total_boosters_per_hundred',
    'new_vaccinations_smoothed_per_million', 'stringency_index',
    'population', 'population_density', 'median_age', 'aged_65_older',
    'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
    'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
    'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
    'life_expectancy', 'human_development_index',
    'excess_mortality_cumulative_absolute', 'excess_mortality_cumulative',
    'excess_mortality', 'excess_mortality_cumulative_per_million'`
    
    2. **`covid_vaccinations`**
        - Drop the following columns:
            - `'total_cases', 'new_cases',
    'new_cases_smoothed', 'total_deaths', 'new_deaths',
    'new_deaths_smoothed', 'total_cases_per_million',
    'new_cases_per_million', 'new_cases_smoothed_per_million',
    'total_deaths_per_million', 'new_deaths_per_million',
    'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
    'icu_patients_per_million', 'hosp_patients',
    'hosp_patients_per_million', 'weekly_icu_admissions',
    'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
    'weekly_hosp_admissions_per_million','population'`

In [97]:
# convert date column to datetime dtype
df['date'] = pd.to_datetime(df['date'])

# create covid_deaths dataframe
covid_deaths = pd.concat(
    [
        df[['iso_code', 'continent', 'location', 'date']],
        df['population'],
        df[['total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million']]
    ],
    axis=1
)

# create covid_vaccinations dataframe 
covid_vaccinations = df.drop(
    [
        'total_cases', 'new_cases',
        'new_cases_smoothed', 'total_deaths', 'new_deaths',
        'new_deaths_smoothed', 'total_cases_per_million',
        'new_cases_per_million', 'new_cases_smoothed_per_million',
        'total_deaths_per_million', 'new_deaths_per_million',
        'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
        'icu_patients_per_million', 'hosp_patients',
        'hosp_patients_per_million', 'weekly_icu_admissions',
        'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
        'weekly_hosp_admissions_per_million','population'
    ],
    axis=1
)

In [77]:
# check
covid_deaths

,iso_code,continent,location,date,population,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,...,new_deaths_smoothed_per_million,reproduction_rate,icu_patients,icu_patients_per_million,hosp_patients,hosp_patients_per_million,weekly_icu_admissions,weekly_icu_admissions_per_million,weekly_hosp_admissions,weekly_hosp_admissions_per_million
0,AFG,Asia,Afghanistan,2020-02-24,39835428.0,5.0,5.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,39835428.0,5.0,0.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120326,ZWE,Africa,Zimbabwe,2021-09-26,15092171.0,129625.0,120.0,241.000,4604.0,1.0,...,0.350,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120327,ZWE,Africa,Zimbabwe,2021-09-27,15092171.0,129919.0,294.0,247.571,4607.0,3.0,...,0.360,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120328,ZWE,Africa,Zimbabwe,2021-09-28,15092171.0,130272.0,353.0,298.000,4615.0,8.0,...,0.435,1.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120329,ZWE,Africa,Zimbabwe,2021-09-29,15092171.0,130485.0,213.0,240.143,4616.0,1.0,...,0.227,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
120330,ZWE,Africa,Zimbabwe,2021-09-30,15092171.0,130820.0,335.0,240.857,4623.0,7.0,...,0.218,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
# check
covid_vaccinations

,iso_code,continent,location,date,new_tests,total_tests,total_tests_per_thousand,new_tests_per_thousand,new_tests_smoothed,new_tests_smoothed_per_thousand,...,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index,excess_mortality_cumulative_absolute,excess_mortality_cumulative,excess_mortality,excess_mortality_cumulative_per_million
0,AFG,Asia,Afghanistan,2020-02-24,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
1,AFG,Asia,Afghanistan,2020-02-25,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
2,AFG,Asia,Afghanistan,2020-02-26,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
3,AFG,Asia,Afghanistan,2020-02-27,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
4,AFG,Asia,Afghanistan,2020-02-28,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,37.746,0.5,64.83,0.511,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
120326,ZWE,Africa,Zimbabwe,2021-09-26,2248.0,1247592.0,82.665,0.149,4736.0,0.314,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
120327,ZWE,Africa,Zimbabwe,2021-09-27,NaN,NaN,NaN,NaN,NaN,NaN,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
120328,ZWE,Africa,Zimbabwe,2021-09-28,NaN,NaN,NaN,NaN,NaN,NaN,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
120329,ZWE,Africa,Zimbabwe,2021-09-29,NaN,NaN,NaN,NaN,NaN,NaN,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN
120330,ZWE,Africa,Zimbabwe,2021-09-30,NaN,NaN,NaN,NaN,NaN,NaN,...,1.6,30.7,36.791,1.7,61.49,0.571,NaN,NaN,NaN,NaN

In [98]:
# export
covid_deaths.to_csv('./data/covid_deaths.csv',index=False)
covid_vaccinations.to_csv('./data/covid_vaccinations.csv',index=False)

---